# Site settings
author: Laura Vlad
title: Data Science in the time of COVID-19
header-img: img/home-bg.png
email: lmvlad@yahoo.com
copyright_name: Laura Vlad
description: > # this means to ignore newlines until "baseurl:"
  A journey from teaching Logic to learning Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauravlad

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
